### ISSUE TITLE
pro2 改的ydkb的蓝牙主控换了这个配置比默认自带的延迟要加很多

### ISSUE THREAD

**Issue by udpsec** [1-2-3/hhkb_ydkb#1]
使用默认自带的固件就没有任何延迟  换了这个之后打字快点延迟就出来了。。不知道你有没遇到

**Comment by 1-2-3** [comment]
我也是 HHKB PRO2，一点延迟都感觉不出来。按理说这个是最新的固件，应该是BUG最少的。要不你去官网[http://ydkb.io/](http://ydkb.io/)，点击“选择键盘”，然后选择“HHKB BLE”， 然后在菜单“下载与分享”中选择“下载.bin”固件，下载下来的是最新K1S的默认固件，看看还有没有延迟。有任何问题再探讨^_^

**Comment by udpsec** [comment]
嗯试了  只要连打速度快点就会错误  物理蓝牙重置也重置了  除非是慢打  自己手速慢点 打一点回车 不然就会出错

**Comment by 1-2-3** [comment]
> 嗯试了 只要连打速度快点就会错误 物理蓝牙重置也重置了 除非是慢打 自己手速慢点 打一点回车 不然就会出错

我以前遇到过 `Word+搜狗输入法+蓝牙连接 ` 的情况下输入太快会有输出重复的字符或者漏掉第一个字符的问题，如果用USB线连接或者不是在Word里或者换QQ输入法都没问题。后来使用了最新的 K1S 固件之后这个问题也解决了。如果你已经更新了 K1S 固件还是不行的话，可以试试换一块主控板子试试。不知道是不是主控板子的个体差异。

**Comment by udpsec** [comment]
问题找到了 空格开启层就会卡延迟 我把他空格开层取消了 设置到别的按键就非常丝滑了

**Comment by 1-2-3** [comment]
> 问题找到了 空格开启层就会卡延迟 我把他空格开层取消了 设置到别的按键就非常丝滑了

原来是这样！但我用空格开启层并没有延迟，可能是板子的个体差异。我看官网上有个QQ服务群，你可以试试加群问问其他人是否有类似的问题。

**Comment by udpsec** [comment]
嗯嗯 好的，已进群
