### ISSUE TITLE
打的太快的时候空格经常失灵

### ISSUE THREAD

**Issue by CFNull** [1-2-3/hhkb_ydkb#2]
用五笔打字的时候特别明显，空格慢半拍。用原版的固件就不会有这个问题。

**Comment by fxph35** [comment]
看了下文档确实是会有这个问题。

**Comment by 1-2-3** [comment]
> 用五笔打字的时候特别明显，空格慢半拍。用原版的固件就不会有这个问题。

嗯，我是设置了空格按下打开层2，所以是空格键松开时才输出空格。但我用搜狗拼音输入法并没有感觉有不舒服或者失灵的情况。你是用的那款五笔输入法？或者你也试试搜狗拼音看看。

**Comment by fxph35** [comment]
> > 用五笔打字的时候特别明显，空格慢半拍。用原版的固件就不会有这个问题。
> 
> 嗯，我是设置了空格按下打开层2，所以是空格键松开时才输出空格。但我用搜狗拼音输入法并没有感觉有不舒服或者失灵的情况。你是用的那款五笔输入法？或者你也试试搜狗拼音看看。

我用的鼠须管，打慢点没事，快了节奏就不对了，按空格频率高了就会有问题。我把设置到不常用的ESC上面去了。
